language: python
python:
- 3.7
- 3.8
install: pip install -r requirements_dev.txt
script: python setup.py test
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  skip_existing: true
  user: lukhe
  password:
    secure: BSxTZsWl46SYXcX3pQFXNmJHjQfi9hZsTlu3oe2eA/pNjTmzPp73jXykRKk1KnBtDiE2Ox4HlVA4pIAzDZtlg1iVTH7y7wfkJEIrKKdkJb3rbAa6kSSGyPbJNXayiE5x0h2+tU3LAhzvu8uFo5/Y/CLTvGPdi00XQpv+2+0gkvCXOnLHEB3Uk5abWocAh7DX/a/v/C/CmUpKej8LXZDNPL1GWslVXEhbwOYJWHnJqF4yZ3bjTiTmg2ekKHyk7kYCTCyD36efwhPdu9MFRHOrf5mhunTLpaLuh6tfetp7yCiPsds3+C2Jlr4VOCq4uSdYzv7DEQyBWEDjMGIZbzOUoYx288xQJ9YLgx4HcNYG4r3VXAzl/np42KL2vyPCTlnizJUQHv9mgrRJ9aRa+otoe7hE1Iuwm0ZiPz+LXoJontUGN8aVCuMh6q1wyQyvQ2mIrKG0amvk0Y5C1bkD7fwn58r74tAkK2sAjlUAPGus6xfAwTOB+qk94z5keP4pItN7VBd+OQ/jlUT2XmeQ/IqQosiEMtFAcDEgXdqOEgOlXmBxqPVKhhV0Msum8jy3qwZWFNTfn09VX7XzJZUvWBbAcxvHrfNvZbNALfeGNlcTs3i1DRXKJ7hu7vOs3uhkrVeNuklnyTJPHLqRO9oPcvNe0BN0wDUlJdfrmGTZUpnzHKI=
  on:
    tags: true
    repo: lukh/microparcel-tools
